/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing ArgumentDescription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArgumentDescriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ArgumentDescription
        //private ArgumentDescription instance;

        public ArgumentDescriptionTests()
        {
            // TODO uncomment below to create an instance of ArgumentDescription
            //instance = new ArgumentDescription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArgumentDescription
        /// </summary>
        [Fact]
        public void ArgumentDescriptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ArgumentDescription
            //Assert.IsType<ArgumentDescription>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
    }
}
