/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing ChildList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChildListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChildList
        //private ChildList instance;

        public ChildListTests()
        {
            // TODO uncomment below to create an instance of ChildList
            //instance = new ChildList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChildList
        /// </summary>
        [Fact]
        public void ChildListInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChildList
            //Assert.IsType<ChildList>(instance);
        }

        /// <summary>
        /// Test the property 'A'
        /// </summary>
        [Fact]
        public void ATest()
        {
            // TODO unit test for the property 'A'
        }

        /// <summary>
        /// Test the property 'B'
        /// </summary>
        [Fact]
        public void BTest()
        {
            // TODO unit test for the property 'B'
        }

        /// <summary>
        /// Test the property 'C'
        /// </summary>
        [Fact]
        public void CTest()
        {
            // TODO unit test for the property 'C'
        }
    }
}
