/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing DataTypeField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataTypeFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataTypeField
        //private DataTypeField instance;

        public DataTypeFieldTests()
        {
            // TODO uncomment below to create an instance of DataTypeField
            //instance = new DataTypeField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataTypeField
        /// </summary>
        [Fact]
        public void DataTypeFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataTypeField
            //Assert.IsType<DataTypeField>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'SymbolicName'
        /// </summary>
        [Fact]
        public void SymbolicNameTest()
        {
            // TODO unit test for the property 'SymbolicName'
        }

        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Fact]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }

        /// <summary>
        /// Test the property 'ValueRank'
        /// </summary>
        [Fact]
        public void ValueRankTest()
        {
            // TODO unit test for the property 'ValueRank'
        }

        /// <summary>
        /// Test the property 'ArrayDimensions'
        /// </summary>
        [Fact]
        public void ArrayDimensionsTest()
        {
            // TODO unit test for the property 'ArrayDimensions'
        }

        /// <summary>
        /// Test the property 'MaxStringLength'
        /// </summary>
        [Fact]
        public void MaxStringLengthTest()
        {
            // TODO unit test for the property 'MaxStringLength'
        }

        /// <summary>
        /// Test the property 'IsOptional'
        /// </summary>
        [Fact]
        public void IsOptionalTest()
        {
            // TODO unit test for the property 'IsOptional'
        }

        /// <summary>
        /// Test the property 'AllowSubTypes'
        /// </summary>
        [Fact]
        public void AllowSubTypesTest()
        {
            // TODO unit test for the property 'AllowSubTypes'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
