/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing DataTypeDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataTypeDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataTypeDefinition
        //private DataTypeDefinition instance;

        public DataTypeDefinitionTests()
        {
            // TODO uncomment below to create an instance of DataTypeDefinition
            //instance = new DataTypeDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataTypeDefinition
        /// </summary>
        [Fact]
        public void DataTypeDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataTypeDefinition
            //Assert.IsType<DataTypeDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'SymbolicName'
        /// </summary>
        [Fact]
        public void SymbolicNameTest()
        {
            // TODO unit test for the property 'SymbolicName'
        }

        /// <summary>
        /// Test the property 'IsUnion'
        /// </summary>
        [Fact]
        public void IsUnionTest()
        {
            // TODO unit test for the property 'IsUnion'
        }

        /// <summary>
        /// Test the property 'IsOptionSet'
        /// </summary>
        [Fact]
        public void IsOptionSetTest()
        {
            // TODO unit test for the property 'IsOptionSet'
        }

        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
    }
}
