/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing FileSetInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileSetInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileSetInfo
        //private FileSetInfo instance;

        public FileSetInfoTests()
        {
            // TODO uncomment below to create an instance of FileSetInfo
            //instance = new FileSetInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileSetInfo
        /// </summary>
        [Fact]
        public void FileSetInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileSetInfo
            //Assert.IsType<FileSetInfo>(instance);
        }

        /// <summary>
        /// Test the property 'CurrentFileNumber'
        /// </summary>
        [Fact]
        public void CurrentFileNumberTest()
        {
            // TODO unit test for the property 'CurrentFileNumber'
        }

        /// <summary>
        /// Test the property 'LastFileNumber'
        /// </summary>
        [Fact]
        public void LastFileNumberTest()
        {
            // TODO unit test for the property 'LastFileNumber'
        }
    }
}
