/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing ModelTableEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelTableEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelTableEntry
        //private ModelTableEntry instance;

        public ModelTableEntryTests()
        {
            // TODO uncomment below to create an instance of ModelTableEntry
            //instance = new ModelTableEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelTableEntry
        /// </summary>
        [Fact]
        public void ModelTableEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelTableEntry
            //Assert.IsType<ModelTableEntry>(instance);
        }

        /// <summary>
        /// Test the property 'ModelUri'
        /// </summary>
        [Fact]
        public void ModelUriTest()
        {
            // TODO unit test for the property 'ModelUri'
        }

        /// <summary>
        /// Test the property 'XmlSchemaUri'
        /// </summary>
        [Fact]
        public void XmlSchemaUriTest()
        {
            // TODO unit test for the property 'XmlSchemaUri'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'PublicationDate'
        /// </summary>
        [Fact]
        public void PublicationDateTest()
        {
            // TODO unit test for the property 'PublicationDate'
        }

        /// <summary>
        /// Test the property 'ModelVersion'
        /// </summary>
        [Fact]
        public void ModelVersionTest()
        {
            // TODO unit test for the property 'ModelVersion'
        }

        /// <summary>
        /// Test the property 'AccessRestrictions'
        /// </summary>
        [Fact]
        public void AccessRestrictionsTest()
        {
            // TODO unit test for the property 'AccessRestrictions'
        }

        /// <summary>
        /// Test the property 'RequiredModel'
        /// </summary>
        [Fact]
        public void RequiredModelTest()
        {
            // TODO unit test for the property 'RequiredModel'
        }
    }
}
