/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing ModelReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelReference
        //private ModelReference instance;

        public ModelReferenceTests()
        {
            // TODO uncomment below to create an instance of ModelReference
            //instance = new ModelReference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelReference
        /// </summary>
        [Fact]
        public void ModelReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelReference
            //Assert.IsType<ModelReference>(instance);
        }

        /// <summary>
        /// Test the property 'ModelUri'
        /// </summary>
        [Fact]
        public void ModelUriTest()
        {
            // TODO unit test for the property 'ModelUri'
        }

        /// <summary>
        /// Test the property 'XmlSchemaUri'
        /// </summary>
        [Fact]
        public void XmlSchemaUriTest()
        {
            // TODO unit test for the property 'XmlSchemaUri'
        }

        /// <summary>
        /// Test the property 'PublicationDate'
        /// </summary>
        [Fact]
        public void PublicationDateTest()
        {
            // TODO unit test for the property 'PublicationDate'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'ModelVersion'
        /// </summary>
        [Fact]
        public void ModelVersionTest()
        {
            // TODO unit test for the property 'ModelVersion'
        }
    }
}
