/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing Reference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Reference
        //private Reference instance;

        public ReferenceTests()
        {
            // TODO uncomment below to create an instance of Reference
            //instance = new Reference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Reference
        /// </summary>
        [Fact]
        public void ReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Reference
            //Assert.IsType<Reference>(instance);
        }

        /// <summary>
        /// Test the property 'ReferenceType'
        /// </summary>
        [Fact]
        public void ReferenceTypeTest()
        {
            // TODO unit test for the property 'ReferenceType'
        }

        /// <summary>
        /// Test the property 'IsForward'
        /// </summary>
        [Fact]
        public void IsForwardTest()
        {
            // TODO unit test for the property 'IsForward'
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }
    }
}
