/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing ReleaseStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReleaseStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReleaseStatus
        //private ReleaseStatus instance;

        public ReleaseStatusTests()
        {
            // TODO uncomment below to create an instance of ReleaseStatus
            //instance = new ReleaseStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReleaseStatus
        /// </summary>
        [Fact]
        public void ReleaseStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReleaseStatus
            //Assert.IsType<ReleaseStatus>(instance);
        }
    }
}
