/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing UAMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UAMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UAMethod
        //private UAMethod instance;

        public UAMethodTests()
        {
            // TODO uncomment below to create an instance of UAMethod
            //instance = new UAMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UAMethod
        /// </summary>
        [Fact]
        public void UAMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" UAMethod
            //Assert.IsType<UAMethod>(instance);
        }

        /// <summary>
        /// Test the property 'NodeId'
        /// </summary>
        [Fact]
        public void NodeIdTest()
        {
            // TODO unit test for the property 'NodeId'
        }

        /// <summary>
        /// Test the property 'NodeClass'
        /// </summary>
        [Fact]
        public void NodeClassTest()
        {
            // TODO unit test for the property 'NodeClass'
        }

        /// <summary>
        /// Test the property 'SymbolicName'
        /// </summary>
        [Fact]
        public void SymbolicNameTest()
        {
            // TODO unit test for the property 'SymbolicName'
        }

        /// <summary>
        /// Test the property 'BrowseName'
        /// </summary>
        [Fact]
        public void BrowseNameTest()
        {
            // TODO unit test for the property 'BrowseName'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'WriteMask'
        /// </summary>
        [Fact]
        public void WriteMaskTest()
        {
            // TODO unit test for the property 'WriteMask'
        }

        /// <summary>
        /// Test the property 'HasNoPermissions'
        /// </summary>
        [Fact]
        public void HasNoPermissionsTest()
        {
            // TODO unit test for the property 'HasNoPermissions'
        }

        /// <summary>
        /// Test the property 'References'
        /// </summary>
        [Fact]
        public void ReferencesTest()
        {
            // TODO unit test for the property 'References'
        }

        /// <summary>
        /// Test the property 'Documentation'
        /// </summary>
        [Fact]
        public void DocumentationTest()
        {
            // TODO unit test for the property 'Documentation'
        }

        /// <summary>
        /// Test the property 'ReleaseStatus'
        /// </summary>
        [Fact]
        public void ReleaseStatusTest()
        {
            // TODO unit test for the property 'ReleaseStatus'
        }

        /// <summary>
        /// Test the property 'RolePermissions'
        /// </summary>
        [Fact]
        public void RolePermissionsTest()
        {
            // TODO unit test for the property 'RolePermissions'
        }

        /// <summary>
        /// Test the property 'AccessRestrictions'
        /// </summary>
        [Fact]
        public void AccessRestrictionsTest()
        {
            // TODO unit test for the property 'AccessRestrictions'
        }

        /// <summary>
        /// Test the property 'ConformationUnit'
        /// </summary>
        [Fact]
        public void ConformationUnitTest()
        {
            // TODO unit test for the property 'ConformationUnit'
        }

        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }

        /// <summary>
        /// Test the property 'ParentNodeId'
        /// </summary>
        [Fact]
        public void ParentNodeIdTest()
        {
            // TODO unit test for the property 'ParentNodeId'
        }

        /// <summary>
        /// Test the property 'DesignToolOnly'
        /// </summary>
        [Fact]
        public void DesignToolOnlyTest()
        {
            // TODO unit test for the property 'DesignToolOnly'
        }

        /// <summary>
        /// Test the property 'Executable'
        /// </summary>
        [Fact]
        public void ExecutableTest()
        {
            // TODO unit test for the property 'Executable'
        }

        /// <summary>
        /// Test the property 'MethodDeclarationId'
        /// </summary>
        [Fact]
        public void MethodDeclarationIdTest()
        {
            // TODO unit test for the property 'MethodDeclarationId'
        }

        /// <summary>
        /// Test the property 'Arguments'
        /// </summary>
        [Fact]
        public void ArgumentsTest()
        {
            // TODO unit test for the property 'Arguments'
        }
    }
}
