/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing UANodeSet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UANodeSetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UANodeSet
        //private UANodeSet instance;

        public UANodeSetTests()
        {
            // TODO uncomment below to create an instance of UANodeSet
            //instance = new UANodeSet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UANodeSet
        /// </summary>
        [Fact]
        public void UANodeSetInstanceTest()
        {
            // TODO uncomment below to test "IsType" UANodeSet
            //Assert.IsType<UANodeSet>(instance);
        }

        /// <summary>
        /// Test the property 'NamespaceUris'
        /// </summary>
        [Fact]
        public void NamespaceUrisTest()
        {
            // TODO unit test for the property 'NamespaceUris'
        }

        /// <summary>
        /// Test the property 'ServerUris'
        /// </summary>
        [Fact]
        public void ServerUrisTest()
        {
            // TODO unit test for the property 'ServerUris'
        }

        /// <summary>
        /// Test the property 'Models'
        /// </summary>
        [Fact]
        public void ModelsTest()
        {
            // TODO unit test for the property 'Models'
        }

        /// <summary>
        /// Test the property 'Nodes'
        /// </summary>
        [Fact]
        public void NodesTest()
        {
            // TODO unit test for the property 'Nodes'
        }
    }
}
