/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opc.Ua.JsonNodeSet.Model;
using Opc.Ua.JsonNodeSet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opc.Ua.JsonNodeSet.Test.Model
{
    /// <summary>
    ///  Class for testing UANodeSetNodes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UANodeSetNodesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UANodeSetNodes
        //private UANodeSetNodes instance;

        public UANodeSetNodesTests()
        {
            // TODO uncomment below to create an instance of UANodeSetNodes
            //instance = new UANodeSetNodes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UANodeSetNodes
        /// </summary>
        [Fact]
        public void UANodeSetNodesInstanceTest()
        {
            // TODO uncomment below to test "IsType" UANodeSetNodes
            //Assert.IsType<UANodeSetNodes>(instance);
        }

        /// <summary>
        /// Test the property 'A'
        /// </summary>
        [Fact]
        public void ATest()
        {
            // TODO unit test for the property 'A'
        }

        /// <summary>
        /// Test the property 'B'
        /// </summary>
        [Fact]
        public void BTest()
        {
            // TODO unit test for the property 'B'
        }

        /// <summary>
        /// Test the property 'C'
        /// </summary>
        [Fact]
        public void CTest()
        {
            // TODO unit test for the property 'C'
        }

        /// <summary>
        /// Test the property 'D'
        /// </summary>
        [Fact]
        public void DTest()
        {
            // TODO unit test for the property 'D'
        }

        /// <summary>
        /// Test the property 'E'
        /// </summary>
        [Fact]
        public void ETest()
        {
            // TODO unit test for the property 'E'
        }

        /// <summary>
        /// Test the property 'F'
        /// </summary>
        [Fact]
        public void FTest()
        {
            // TODO unit test for the property 'F'
        }

        /// <summary>
        /// Test the property 'G'
        /// </summary>
        [Fact]
        public void GTest()
        {
            // TODO unit test for the property 'G'
        }

        /// <summary>
        /// Test the property 'H'
        /// </summary>
        [Fact]
        public void HTest()
        {
            // TODO unit test for the property 'H'
        }
    }
}
