/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// DataTypeField
    /// </summary>
    [DataContract(Name = "DataTypeField")]
    public partial class DataTypeField : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataTypeField" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="symbolicName">symbolicName.</param>
        /// <param name="value">value.</param>
        /// <param name="dataType">dataType.</param>
        /// <param name="valueRank">valueRank.</param>
        /// <param name="arrayDimensions">arrayDimensions.</param>
        /// <param name="maxStringLength">maxStringLength.</param>
        /// <param name="isOptional">isOptional.</param>
        /// <param name="allowSubTypes">allowSubTypes.</param>
        /// <param name="displayName">displayName.</param>
        /// <param name="description">description.</param>
        public DataTypeField(string name = default(string), string symbolicName = default(string), int? value = default(int?), string dataType = default(string), int? valueRank = default(int?), string arrayDimensions = default(string), int? maxStringLength = default(int?), bool? isOptional = default(bool?), bool? allowSubTypes = default(bool?), LocalizedText displayName = default(LocalizedText), LocalizedText description = default(LocalizedText))
        {
            this.Name = name;
            this.SymbolicName = symbolicName;
            this.Value = value;
            this.DataType = dataType;
            this.ValueRank = valueRank;
            this.ArrayDimensions = arrayDimensions;
            this.MaxStringLength = maxStringLength;
            this.IsOptional = isOptional;
            this.AllowSubTypes = allowSubTypes;
            this.DisplayName = displayName;
            this.Description = description;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "Name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets SymbolicName
        /// </summary>
        [DataMember(Name = "SymbolicName", EmitDefaultValue = false)]
        public string SymbolicName { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "Value", EmitDefaultValue = true)]
        public int? Value { get; set; }

        /// <summary>
        /// Gets or Sets DataType
        /// </summary>
        [DataMember(Name = "DataType", EmitDefaultValue = false)]
        public string DataType { get; set; }

        /// <summary>
        /// Gets or Sets ValueRank
        /// </summary>
        [DataMember(Name = "ValueRank", EmitDefaultValue = true)]
        public int? ValueRank { get; set; }

        /// <summary>
        /// Gets or Sets ArrayDimensions
        /// </summary>
        [DataMember(Name = "ArrayDimensions", EmitDefaultValue = false)]
        public string ArrayDimensions { get; set; }

        /// <summary>
        /// Gets or Sets MaxStringLength
        /// </summary>
        [DataMember(Name = "MaxStringLength", EmitDefaultValue = true)]
        public int? MaxStringLength { get; set; }

        /// <summary>
        /// Gets or Sets IsOptional
        /// </summary>
        [DataMember(Name = "IsOptional", EmitDefaultValue = true)]
        public bool? IsOptional { get; set; }

        /// <summary>
        /// Gets or Sets AllowSubTypes
        /// </summary>
        [DataMember(Name = "AllowSubTypes", EmitDefaultValue = true)]
        public bool? AllowSubTypes { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name = "DisplayName", EmitDefaultValue = false)]
        public LocalizedText DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "Description", EmitDefaultValue = false)]
        public LocalizedText Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataTypeField {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SymbolicName: ").Append(SymbolicName).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  DataType: ").Append(DataType).Append("\n");
            sb.Append("  ValueRank: ").Append(ValueRank).Append("\n");
            sb.Append("  ArrayDimensions: ").Append(ArrayDimensions).Append("\n");
            sb.Append("  MaxStringLength: ").Append(MaxStringLength).Append("\n");
            sb.Append("  IsOptional: ").Append(IsOptional).Append("\n");
            sb.Append("  AllowSubTypes: ").Append(AllowSubTypes).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
