/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// DataTypeDefinition
    /// </summary>
    [DataContract(Name = "DataTypeDefinition")]
    public partial class DataTypeDefinition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataTypeDefinition" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="symbolicName">symbolicName.</param>
        /// <param name="isUnion">isUnion.</param>
        /// <param name="isOptionSet">isOptionSet.</param>
        /// <param name="fields">fields.</param>
        public DataTypeDefinition(string name = default(string), string symbolicName = default(string), bool? isUnion = default(bool?), bool? isOptionSet = default(bool?), List<DataTypeField> fields = default(List<DataTypeField>))
        {
            this.Name = name;
            this.SymbolicName = symbolicName;
            this.IsUnion = isUnion;
            this.IsOptionSet = isOptionSet;
            this.Fields = fields;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "Name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets SymbolicName
        /// </summary>
        [DataMember(Name = "SymbolicName", EmitDefaultValue = false)]
        public string SymbolicName { get; set; }

        /// <summary>
        /// Gets or Sets IsUnion
        /// </summary>
        [DataMember(Name = "IsUnion", EmitDefaultValue = true)]
        public bool? IsUnion { get; set; }

        /// <summary>
        /// Gets or Sets IsOptionSet
        /// </summary>
        [DataMember(Name = "IsOptionSet", EmitDefaultValue = true)]
        public bool? IsOptionSet { get; set; }

        /// <summary>
        /// Gets or Sets Fields
        /// </summary>
        [DataMember(Name = "Fields", EmitDefaultValue = false)]
        public List<DataTypeField> Fields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataTypeDefinition {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SymbolicName: ").Append(SymbolicName).Append("\n");
            sb.Append("  IsUnion: ").Append(IsUnion).Append("\n");
            sb.Append("  IsOptionSet: ").Append(IsOptionSet).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
