/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// Defines DataTypePurpose
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DataTypePurpose
    {
        /// <summary>
        /// Enum Normal for value: Normal
        /// </summary>
        [EnumMember(Value = "Normal")]
        Normal = 1,

        /// <summary>
        /// Enum ServicesOnly for value: ServicesOnly
        /// </summary>
        [EnumMember(Value = "ServicesOnly")]
        ServicesOnly = 2,

        /// <summary>
        /// Enum CodeGenerator for value: CodeGenerator
        /// </summary>
        [EnumMember(Value = "CodeGenerator")]
        CodeGenerator = 3
    }

}
