/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// FileSetInfo
    /// </summary>
    [DataContract(Name = "FileSetInfo")]
    public partial class FileSetInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileSetInfo" /> class.
        /// </summary>
        /// <param name="current">current.</param>
        /// <param name="last">last.</param>
        public FileSetInfo(int current = default(int), int last = default(int))
        {
            this.Current = current;
            this.Last = last;
        }

        /// <summary>
        /// Gets or Sets Current
        /// </summary>
        [DataMember(Name = "Current", EmitDefaultValue = false)]
        public int Current { get; set; }

        /// <summary>
        /// Gets or Sets Last
        /// </summary>
        [DataMember(Name = "Last", EmitDefaultValue = false)]
        public int Last { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FileSetInfo {\n");
            sb.Append("  Current: ").Append(Current).Append("\n");
            sb.Append("  Last: ").Append(Last).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Current (int) maximum
            if (this.Current > (int)65535)
            {
                yield return new ValidationResult("Invalid value for Current, must be a value less than or equal to 65535.", new [] { "Current" });
            }

            // Current (int) minimum
            if (this.Current < (int)0)
            {
                yield return new ValidationResult("Invalid value for Current, must be a value greater than or equal to 0.", new [] { "Current" });
            }

            // Last (int) maximum
            if (this.Last > (int)65535)
            {
                yield return new ValidationResult("Invalid value for Last, must be a value less than or equal to 65535.", new [] { "Last" });
            }

            // Last (int) minimum
            if (this.Last < (int)0)
            {
                yield return new ValidationResult("Invalid value for Last, must be a value greater than or equal to 0.", new [] { "Last" });
            }

            yield break;
        }
    }

}
