/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// ModelDefinition
    /// </summary>
    [DataContract(Name = "ModelDefinition")]
    public partial class ModelDefinition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelDefinition" /> class.
        /// </summary>
        /// <param name="modelUri">modelUri.</param>
        /// <param name="xmlSchemaUri">xmlSchemaUri.</param>
        /// <param name="publicationDate">publicationDate.</param>
        /// <param name="varVersion">varVersion.</param>
        /// <param name="modelVersion">modelVersion.</param>
        /// <param name="defaultAccessRestrictions">defaultAccessRestrictions.</param>
        /// <param name="defaultRolePermissions">defaultRolePermissions.</param>
        /// <param name="requiredModels">requiredModels.</param>
        public ModelDefinition(string modelUri = default(string), string xmlSchemaUri = default(string), DateTime? publicationDate = default(DateTime?), string varVersion = default(string), string modelVersion = default(string), long? defaultAccessRestrictions = default(long?), List<RolePermission> defaultRolePermissions = default(List<RolePermission>), List<ModelReference> requiredModels = default(List<ModelReference>))
        {
            this.ModelUri = modelUri;
            this.XmlSchemaUri = xmlSchemaUri;
            this.PublicationDate = publicationDate;
            this.VarVersion = varVersion;
            this.ModelVersion = modelVersion;
            this.DefaultAccessRestrictions = defaultAccessRestrictions;
            this.DefaultRolePermissions = defaultRolePermissions;
            this.RequiredModels = requiredModels;
        }

        /// <summary>
        /// Gets or Sets ModelUri
        /// </summary>
        [DataMember(Name = "ModelUri", EmitDefaultValue = false)]
        public string ModelUri { get; set; }

        /// <summary>
        /// Gets or Sets XmlSchemaUri
        /// </summary>
        [DataMember(Name = "XmlSchemaUri", EmitDefaultValue = false)]
        public string XmlSchemaUri { get; set; }

        /// <summary>
        /// Gets or Sets PublicationDate
        /// </summary>
        [DataMember(Name = "PublicationDate", EmitDefaultValue = true)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime? PublicationDate { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [DataMember(Name = "Version", EmitDefaultValue = false)]
        public string VarVersion { get; set; }

        /// <summary>
        /// Gets or Sets ModelVersion
        /// </summary>
        [DataMember(Name = "ModelVersion", EmitDefaultValue = false)]
        public string ModelVersion { get; set; }

        /// <summary>
        /// Gets or Sets DefaultAccessRestrictions
        /// </summary>
        [DataMember(Name = "DefaultAccessRestrictions", EmitDefaultValue = true)]
        public long? DefaultAccessRestrictions { get; set; }

        /// <summary>
        /// Gets or Sets DefaultRolePermissions
        /// </summary>
        [DataMember(Name = "DefaultRolePermissions", EmitDefaultValue = false)]
        public List<RolePermission> DefaultRolePermissions { get; set; }

        /// <summary>
        /// Gets or Sets RequiredModels
        /// </summary>
        [DataMember(Name = "RequiredModels", EmitDefaultValue = false)]
        public List<ModelReference> RequiredModels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ModelDefinition {\n");
            sb.Append("  ModelUri: ").Append(ModelUri).Append("\n");
            sb.Append("  XmlSchemaUri: ").Append(XmlSchemaUri).Append("\n");
            sb.Append("  PublicationDate: ").Append(PublicationDate).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  ModelVersion: ").Append(ModelVersion).Append("\n");
            sb.Append("  DefaultAccessRestrictions: ").Append(DefaultAccessRestrictions).Append("\n");
            sb.Append("  DefaultRolePermissions: ").Append(DefaultRolePermissions).Append("\n");
            sb.Append("  RequiredModels: ").Append(RequiredModels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DefaultAccessRestrictions (long?) maximum
            if (this.DefaultAccessRestrictions > (long?)4294967296)
            {
                yield return new ValidationResult("Invalid value for DefaultAccessRestrictions, must be a value less than or equal to 4294967296.", new [] { "DefaultAccessRestrictions" });
            }

            // DefaultAccessRestrictions (long?) minimum
            if (this.DefaultAccessRestrictions < (long?)0)
            {
                yield return new ValidationResult("Invalid value for DefaultAccessRestrictions, must be a value greater than or equal to 0.", new [] { "DefaultAccessRestrictions" });
            }

            yield break;
        }
    }

}
