/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// ModelReference
    /// </summary>
    [DataContract(Name = "ModelReference")]
    public partial class ModelReference : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelReference" /> class.
        /// </summary>
        /// <param name="modelUri">modelUri.</param>
        /// <param name="xmlSchemaUri">xmlSchemaUri.</param>
        /// <param name="publicationDate">publicationDate.</param>
        /// <param name="varVersion">varVersion.</param>
        /// <param name="modelVersion">modelVersion.</param>
        public ModelReference(string modelUri = default(string), string xmlSchemaUri = default(string), DateTime? publicationDate = default(DateTime?), string varVersion = default(string), string modelVersion = default(string))
        {
            this.ModelUri = modelUri;
            this.XmlSchemaUri = xmlSchemaUri;
            this.PublicationDate = publicationDate;
            this.VarVersion = varVersion;
            this.ModelVersion = modelVersion;
        }

        /// <summary>
        /// Gets or Sets ModelUri
        /// </summary>
        [DataMember(Name = "ModelUri", EmitDefaultValue = false)]
        public string ModelUri { get; set; }

        /// <summary>
        /// Gets or Sets XmlSchemaUri
        /// </summary>
        [DataMember(Name = "XmlSchemaUri", EmitDefaultValue = false)]
        public string XmlSchemaUri { get; set; }

        /// <summary>
        /// Gets or Sets PublicationDate
        /// </summary>
        [DataMember(Name = "PublicationDate", EmitDefaultValue = true)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime? PublicationDate { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [DataMember(Name = "Version", EmitDefaultValue = false)]
        public string VarVersion { get; set; }

        /// <summary>
        /// Gets or Sets ModelVersion
        /// </summary>
        [DataMember(Name = "ModelVersion", EmitDefaultValue = false)]
        public string ModelVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ModelReference {\n");
            sb.Append("  ModelUri: ").Append(ModelUri).Append("\n");
            sb.Append("  XmlSchemaUri: ").Append(XmlSchemaUri).Append("\n");
            sb.Append("  PublicationDate: ").Append(PublicationDate).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  ModelVersion: ").Append(ModelVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
