/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// Defines NodeClass
    /// </summary>
    public enum NodeClass
    {
        /// <summary>
        /// Enum Unspecified for value: 0
        /// </summary>
        Unspecified = 0,

        /// <summary>
        /// Enum UAObject for value: 1
        /// </summary>
        UAObject = 1,

        /// <summary>
        /// Enum UAVariable for value: 2
        /// </summary>
        UAVariable = 2,

        /// <summary>
        /// Enum UAMethod for value: 4
        /// </summary>
        UAMethod = 4,

        /// <summary>
        /// Enum UAObjectType for value: 8
        /// </summary>
        UAObjectType = 8,

        /// <summary>
        /// Enum UAVariableType for value: 16
        /// </summary>
        UAVariableType = 16,

        /// <summary>
        /// Enum UAReferenceType for value: 32
        /// </summary>
        UAReferenceType = 32,

        /// <summary>
        /// Enum UADataType for value: 64
        /// </summary>
        UADataType = 64,

        /// <summary>
        /// Enum UAView for value: 128
        /// </summary>
        UAView = 128
    }

}
