/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// Defines ReleaseStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ReleaseStatus
    {
        /// <summary>
        /// Enum Released for value: Released
        /// </summary>
        [EnumMember(Value = "Released")]
        Released = 1,

        /// <summary>
        /// Enum Draft for value: Draft
        /// </summary>
        [EnumMember(Value = "Draft")]
        Draft = 2,

        /// <summary>
        /// Enum Deprecated for value: Deprecated
        /// </summary>
        [EnumMember(Value = "Deprecated")]
        Deprecated = 3
    }

}
