/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// UAMethod
    /// </summary>
    [DataContract(Name = "UAMethod")]
    [JsonConverter(typeof(JsonSubtypes), "NodeClass")]
    public partial class UAMethod : UANode, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UAMethod" /> class.
        /// </summary>
        /// <param name="executable">executable.</param>
        /// <param name="methodDeclarationId">methodDeclarationId.</param>
        /// <param name="arguments">arguments.</param>
        /// <param name="nodeId">nodeId.</param>
        /// <param name="nodeClass">nodeClass (default to &quot;UAMethod&quot;).</param>
        /// <param name="symbolicName">symbolicName.</param>
        /// <param name="browseName">browseName.</param>
        /// <param name="displayName">displayName.</param>
        /// <param name="description">description.</param>
        /// <param name="writeMask">writeMask.</param>
        /// <param name="hasNoPermissions">hasNoPermissions.</param>
        /// <param name="references">references.</param>
        /// <param name="documentation">documentation.</param>
        /// <param name="releaseStatus">releaseStatus.</param>
        /// <param name="rolePermissions">rolePermissions.</param>
        /// <param name="accessRestrictions">accessRestrictions.</param>
        /// <param name="conformationUnits">conformationUnits.</param>
        /// <param name="parentId">parentId.</param>
        /// <param name="typeId">typeId.</param>
        /// <param name="modellingRuleId">modellingRuleId.</param>
        /// <param name="designToolOnly">designToolOnly.</param>
        /// <param name="isAbstract">isAbstract.</param>
        /// <param name="children">children.</param>
        public UAMethod(bool? executable = default(bool?), string methodDeclarationId = default(string), List<ArgumentDescription> arguments = default(List<ArgumentDescription>), string nodeId = default(string), NodeClass? nodeClass = Model.NodeClass.UAMethod, string symbolicName = default(string), string browseName = default(string), LocalizedText displayName = default(LocalizedText), LocalizedText description = default(LocalizedText), long? writeMask = default(long?), bool? hasNoPermissions = default(bool?), List<Reference> references = default(List<Reference>), string documentation = default(string), ReleaseStatus? releaseStatus = default(ReleaseStatus?), List<RolePermission> rolePermissions = default(List<RolePermission>), long? accessRestrictions = default(long?), List<string> conformationUnits = default(List<string>), string parentId = default(string), string typeId = default(string), string modellingRuleId = default(string), bool? designToolOnly = default(bool?), bool? isAbstract = default(bool?), ChildList children = default(ChildList)) : base(nodeId, nodeClass, symbolicName, browseName, displayName, description, writeMask, hasNoPermissions, references, documentation, releaseStatus, rolePermissions, accessRestrictions, conformationUnits, parentId, typeId, modellingRuleId, designToolOnly, isAbstract, children)
        {
            this.Executable = executable;
            this.MethodDeclarationId = methodDeclarationId;
            this.Arguments = arguments;
        }

        /// <summary>
        /// Gets or Sets Executable
        /// </summary>
        [DataMember(Name = "Executable", EmitDefaultValue = true)]
        public bool? Executable { get; set; }

        /// <summary>
        /// Gets or Sets MethodDeclarationId
        /// </summary>
        [DataMember(Name = "MethodDeclarationId", EmitDefaultValue = false)]
        public string MethodDeclarationId { get; set; }

        /// <summary>
        /// Gets or Sets Arguments
        /// </summary>
        [DataMember(Name = "Arguments", EmitDefaultValue = false)]
        public List<ArgumentDescription> Arguments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UAMethod {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Executable: ").Append(Executable).Append("\n");
            sb.Append("  MethodDeclarationId: ").Append(MethodDeclarationId).Append("\n");
            sb.Append("  Arguments: ").Append(Arguments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected override IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
