/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// UANodeSet
    /// </summary>
    [DataContract(Name = "UANodeSet")]
    public partial class UANodeSet : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UANodeSet" /> class.
        /// </summary>
        /// <param name="models">models.</param>
        /// <param name="fileSet">fileSet.</param>
        /// <param name="nodes">nodes.</param>
        public UANodeSet(List<ModelDefinition> models = default(List<ModelDefinition>), FileSetInfo fileSet = default(FileSetInfo), UANodeSetNodes nodes = default(UANodeSetNodes))
        {
            this.Models = models;
            this.FileSet = fileSet;
            this.Nodes = nodes;
        }

        /// <summary>
        /// Gets or Sets Models
        /// </summary>
        [DataMember(Name = "Models", EmitDefaultValue = false)]
        public List<ModelDefinition> Models { get; set; }

        /// <summary>
        /// Gets or Sets FileSet
        /// </summary>
        [DataMember(Name = "FileSet", EmitDefaultValue = false)]
        public FileSetInfo FileSet { get; set; }

        /// <summary>
        /// Gets or Sets Nodes
        /// </summary>
        [DataMember(Name = "Nodes", EmitDefaultValue = false)]
        public UANodeSetNodes Nodes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UANodeSet {\n");
            sb.Append("  Models: ").Append(Models).Append("\n");
            sb.Append("  FileSet: ").Append(FileSet).Append("\n");
            sb.Append("  Nodes: ").Append(Nodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
