/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// UANodeSetNodes
    /// </summary>
    [DataContract(Name = "UANodeSet_Nodes")]
    public partial class UANodeSetNodes : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UANodeSetNodes" /> class.
        /// </summary>
        /// <param name="n1ReferenceTypes">n1ReferenceTypes.</param>
        /// <param name="n2DataTypes">n2DataTypes.</param>
        /// <param name="n3VariableTypes">n3VariableTypes.</param>
        /// <param name="n4ObjectTypes">n4ObjectTypes.</param>
        /// <param name="n5Variables">n5Variables.</param>
        /// <param name="n6Methods">n6Methods.</param>
        /// <param name="n7Objects">n7Objects.</param>
        /// <param name="n8Views">n8Views.</param>
        public UANodeSetNodes(List<UAReferenceType> n1ReferenceTypes = default(List<UAReferenceType>), List<UADataType> n2DataTypes = default(List<UADataType>), List<UAVariableType> n3VariableTypes = default(List<UAVariableType>), List<UAObjectType> n4ObjectTypes = default(List<UAObjectType>), List<UAVariable> n5Variables = default(List<UAVariable>), List<UAMethod> n6Methods = default(List<UAMethod>), List<UAObject> n7Objects = default(List<UAObject>), List<UAView> n8Views = default(List<UAView>))
        {
            this.N1ReferenceTypes = n1ReferenceTypes;
            this.N2DataTypes = n2DataTypes;
            this.N3VariableTypes = n3VariableTypes;
            this.N4ObjectTypes = n4ObjectTypes;
            this.N5Variables = n5Variables;
            this.N6Methods = n6Methods;
            this.N7Objects = n7Objects;
            this.N8Views = n8Views;
        }

        /// <summary>
        /// Gets or Sets N1ReferenceTypes
        /// </summary>
        [DataMember(Name = "N1ReferenceTypes", EmitDefaultValue = false)]
        public List<UAReferenceType> N1ReferenceTypes { get; set; }

        /// <summary>
        /// Gets or Sets N2DataTypes
        /// </summary>
        [DataMember(Name = "N2DataTypes", EmitDefaultValue = false)]
        public List<UADataType> N2DataTypes { get; set; }

        /// <summary>
        /// Gets or Sets N3VariableTypes
        /// </summary>
        [DataMember(Name = "N3VariableTypes", EmitDefaultValue = false)]
        public List<UAVariableType> N3VariableTypes { get; set; }

        /// <summary>
        /// Gets or Sets N4ObjectTypes
        /// </summary>
        [DataMember(Name = "N4ObjectTypes", EmitDefaultValue = false)]
        public List<UAObjectType> N4ObjectTypes { get; set; }

        /// <summary>
        /// Gets or Sets N5Variables
        /// </summary>
        [DataMember(Name = "N5Variables", EmitDefaultValue = false)]
        public List<UAVariable> N5Variables { get; set; }

        /// <summary>
        /// Gets or Sets N6Methods
        /// </summary>
        [DataMember(Name = "N6Methods", EmitDefaultValue = false)]
        public List<UAMethod> N6Methods { get; set; }

        /// <summary>
        /// Gets or Sets N7Objects
        /// </summary>
        [DataMember(Name = "N7Objects", EmitDefaultValue = false)]
        public List<UAObject> N7Objects { get; set; }

        /// <summary>
        /// Gets or Sets N8Views
        /// </summary>
        [DataMember(Name = "N8Views", EmitDefaultValue = false)]
        public List<UAView> N8Views { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UANodeSetNodes {\n");
            sb.Append("  N1ReferenceTypes: ").Append(N1ReferenceTypes).Append("\n");
            sb.Append("  N2DataTypes: ").Append(N2DataTypes).Append("\n");
            sb.Append("  N3VariableTypes: ").Append(N3VariableTypes).Append("\n");
            sb.Append("  N4ObjectTypes: ").Append(N4ObjectTypes).Append("\n");
            sb.Append("  N5Variables: ").Append(N5Variables).Append("\n");
            sb.Append("  N6Methods: ").Append(N6Methods).Append("\n");
            sb.Append("  N7Objects: ").Append(N7Objects).Append("\n");
            sb.Append("  N8Views: ").Append(N8Views).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
