/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// UANode
    /// </summary>
    [DataContract(Name = "UANode")]
    [JsonConverter(typeof(JsonSubtypes), "NodeClass")]
    [JsonSubtypes.KnownSubType(typeof(UAObject), "1")]
    [JsonSubtypes.KnownSubType(typeof(UAView), "128")]
    [JsonSubtypes.KnownSubType(typeof(UAVariableType), "16")]
    [JsonSubtypes.KnownSubType(typeof(UAVariable), "2")]
    [JsonSubtypes.KnownSubType(typeof(UAReferenceType), "32")]
    [JsonSubtypes.KnownSubType(typeof(UAMethod), "4")]
    [JsonSubtypes.KnownSubType(typeof(UADataType), "64")]
    [JsonSubtypes.KnownSubType(typeof(UAObjectType), "8")]
    public partial class UANode : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets NodeClass
        /// </summary>
        [DataMember(Name = "NodeClass", EmitDefaultValue = false)]
        public NodeClass? NodeClass { get; set; }

        /// <summary>
        /// Gets or Sets ReleaseStatus
        /// </summary>
        [DataMember(Name = "ReleaseStatus", EmitDefaultValue = false)]
        public ReleaseStatus? ReleaseStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UANode" /> class.
        /// </summary>
        /// <param name="nodeId">nodeId.</param>
        /// <param name="nodeClass">nodeClass.</param>
        /// <param name="symbolicName">symbolicName.</param>
        /// <param name="browseName">browseName.</param>
        /// <param name="displayName">displayName.</param>
        /// <param name="description">description.</param>
        /// <param name="writeMask">writeMask.</param>
        /// <param name="hasNoPermissions">hasNoPermissions.</param>
        /// <param name="references">references.</param>
        /// <param name="documentation">documentation.</param>
        /// <param name="releaseStatus">releaseStatus.</param>
        /// <param name="rolePermissions">rolePermissions.</param>
        /// <param name="accessRestrictions">accessRestrictions.</param>
        /// <param name="conformationUnits">conformationUnits.</param>
        /// <param name="parentId">parentId.</param>
        /// <param name="typeId">typeId.</param>
        /// <param name="modellingRuleId">modellingRuleId.</param>
        /// <param name="designToolOnly">designToolOnly.</param>
        /// <param name="isAbstract">isAbstract.</param>
        /// <param name="children">children.</param>
        public UANode(string nodeId = default(string), NodeClass? nodeClass = default(NodeClass?), string symbolicName = default(string), string browseName = default(string), LocalizedText displayName = default(LocalizedText), LocalizedText description = default(LocalizedText), long? writeMask = default(long?), bool? hasNoPermissions = default(bool?), List<Reference> references = default(List<Reference>), string documentation = default(string), ReleaseStatus? releaseStatus = default(ReleaseStatus?), List<RolePermission> rolePermissions = default(List<RolePermission>), long? accessRestrictions = default(long?), List<string> conformationUnits = default(List<string>), string parentId = default(string), string typeId = default(string), string modellingRuleId = default(string), bool? designToolOnly = default(bool?), bool? isAbstract = default(bool?), ChildList children = default(ChildList))
        {
            this.NodeId = nodeId;
            this.NodeClass = nodeClass;
            this.SymbolicName = symbolicName;
            this.BrowseName = browseName;
            this.DisplayName = displayName;
            this.Description = description;
            this.WriteMask = writeMask;
            this.HasNoPermissions = hasNoPermissions;
            this.References = references;
            this.Documentation = documentation;
            this.ReleaseStatus = releaseStatus;
            this.RolePermissions = rolePermissions;
            this.AccessRestrictions = accessRestrictions;
            this.ConformationUnits = conformationUnits;
            this.ParentId = parentId;
            this.TypeId = typeId;
            this.ModellingRuleId = modellingRuleId;
            this.DesignToolOnly = designToolOnly;
            this.IsAbstract = isAbstract;
            this.Children = children;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets NodeId
        /// </summary>
        [DataMember(Name = "NodeId", EmitDefaultValue = false)]
        public string NodeId { get; set; }

        /// <summary>
        /// Gets or Sets SymbolicName
        /// </summary>
        [DataMember(Name = "SymbolicName", EmitDefaultValue = false)]
        public string SymbolicName { get; set; }

        /// <summary>
        /// Gets or Sets BrowseName
        /// </summary>
        [DataMember(Name = "BrowseName", EmitDefaultValue = false)]
        public string BrowseName { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name = "DisplayName", EmitDefaultValue = false)]
        public LocalizedText DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "Description", EmitDefaultValue = false)]
        public LocalizedText Description { get; set; }

        /// <summary>
        /// Gets or Sets WriteMask
        /// </summary>
        [DataMember(Name = "WriteMask", EmitDefaultValue = true)]
        public long? WriteMask { get; set; }

        /// <summary>
        /// Gets or Sets HasNoPermissions
        /// </summary>
        [DataMember(Name = "HasNoPermissions", EmitDefaultValue = true)]
        public bool? HasNoPermissions { get; set; }

        /// <summary>
        /// Gets or Sets References
        /// </summary>
        [DataMember(Name = "References", EmitDefaultValue = false)]
        public List<Reference> References { get; set; }

        /// <summary>
        /// Gets or Sets Documentation
        /// </summary>
        [DataMember(Name = "Documentation", EmitDefaultValue = false)]
        public string Documentation { get; set; }

        /// <summary>
        /// Gets or Sets RolePermissions
        /// </summary>
        [DataMember(Name = "RolePermissions", EmitDefaultValue = false)]
        public List<RolePermission> RolePermissions { get; set; }

        /// <summary>
        /// Gets or Sets AccessRestrictions
        /// </summary>
        [DataMember(Name = "AccessRestrictions", EmitDefaultValue = true)]
        public long? AccessRestrictions { get; set; }

        /// <summary>
        /// Gets or Sets ConformationUnits
        /// </summary>
        [DataMember(Name = "ConformationUnits", EmitDefaultValue = false)]
        public List<string> ConformationUnits { get; set; }

        /// <summary>
        /// Gets or Sets ParentId
        /// </summary>
        [DataMember(Name = "ParentId", EmitDefaultValue = false)]
        public string ParentId { get; set; }

        /// <summary>
        /// Gets or Sets TypeId
        /// </summary>
        [DataMember(Name = "TypeId", EmitDefaultValue = false)]
        public string TypeId { get; set; }

        /// <summary>
        /// Gets or Sets ModellingRuleId
        /// </summary>
        [DataMember(Name = "ModellingRuleId", EmitDefaultValue = false)]
        public string ModellingRuleId { get; set; }

        /// <summary>
        /// Gets or Sets DesignToolOnly
        /// </summary>
        [DataMember(Name = "DesignToolOnly", EmitDefaultValue = true)]
        public bool? DesignToolOnly { get; set; }

        /// <summary>
        /// Gets or Sets IsAbstract
        /// </summary>
        [DataMember(Name = "IsAbstract", EmitDefaultValue = true)]
        public bool? IsAbstract { get; set; }

        /// <summary>
        /// Gets or Sets Children
        /// </summary>
        [DataMember(Name = "Children", EmitDefaultValue = false)]
        public ChildList Children { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UANode {\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  NodeClass: ").Append(NodeClass).Append("\n");
            sb.Append("  SymbolicName: ").Append(SymbolicName).Append("\n");
            sb.Append("  BrowseName: ").Append(BrowseName).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  WriteMask: ").Append(WriteMask).Append("\n");
            sb.Append("  HasNoPermissions: ").Append(HasNoPermissions).Append("\n");
            sb.Append("  References: ").Append(References).Append("\n");
            sb.Append("  Documentation: ").Append(Documentation).Append("\n");
            sb.Append("  ReleaseStatus: ").Append(ReleaseStatus).Append("\n");
            sb.Append("  RolePermissions: ").Append(RolePermissions).Append("\n");
            sb.Append("  AccessRestrictions: ").Append(AccessRestrictions).Append("\n");
            sb.Append("  ConformationUnits: ").Append(ConformationUnits).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("  TypeId: ").Append(TypeId).Append("\n");
            sb.Append("  ModellingRuleId: ").Append(ModellingRuleId).Append("\n");
            sb.Append("  DesignToolOnly: ").Append(DesignToolOnly).Append("\n");
            sb.Append("  IsAbstract: ").Append(IsAbstract).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected virtual IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            // WriteMask (long?) maximum
            if (this.WriteMask > (long?)4294967296)
            {
                yield return new ValidationResult("Invalid value for WriteMask, must be a value less than or equal to 4294967296.", new [] { "WriteMask" });
            }

            // WriteMask (long?) minimum
            if (this.WriteMask < (long?)0)
            {
                yield return new ValidationResult("Invalid value for WriteMask, must be a value greater than or equal to 0.", new [] { "WriteMask" });
            }

            // AccessRestrictions (long?) maximum
            if (this.AccessRestrictions > (long?)4294967296)
            {
                yield return new ValidationResult("Invalid value for AccessRestrictions, must be a value less than or equal to 4294967296.", new [] { "AccessRestrictions" });
            }

            // AccessRestrictions (long?) minimum
            if (this.AccessRestrictions < (long?)0)
            {
                yield return new ValidationResult("Invalid value for AccessRestrictions, must be a value greater than or equal to 0.", new [] { "AccessRestrictions" });
            }

            yield break;
        }
    }

}
