/*
 * OPC UA NodeSet
 *
 * This is API to access an OPC UA NodeSet.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opc.Ua.JsonNodeSet.Client.OpenAPIDateConverter;

namespace Opc.Ua.JsonNodeSet.Model
{
    /// <summary>
    /// UAVariable
    /// </summary>
    [DataContract(Name = "UAVariable")]
    [JsonConverter(typeof(JsonSubtypes), "NodeClass")]
    public partial class UAVariable : UANode, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UAVariable" /> class.
        /// </summary>
        /// <param name="value">value.</param>
        /// <param name="dataType">dataType.</param>
        /// <param name="valueRank">valueRank (default to -1).</param>
        /// <param name="arrayDimensions">arrayDimensions.</param>
        /// <param name="accessLevel">accessLevel.</param>
        /// <param name="minimumSamplingInterval">minimumSamplingInterval.</param>
        /// <param name="historizing">historizing.</param>
        /// <param name="nodeId">nodeId.</param>
        /// <param name="nodeClass">nodeClass (default to &quot;UAVariable&quot;).</param>
        /// <param name="symbolicName">symbolicName.</param>
        /// <param name="browseName">browseName.</param>
        /// <param name="displayName">displayName.</param>
        /// <param name="description">description.</param>
        /// <param name="writeMask">writeMask.</param>
        /// <param name="hasNoPermissions">hasNoPermissions.</param>
        /// <param name="references">references.</param>
        /// <param name="documentation">documentation.</param>
        /// <param name="releaseStatus">releaseStatus.</param>
        /// <param name="rolePermissions">rolePermissions.</param>
        /// <param name="accessRestrictions">accessRestrictions.</param>
        /// <param name="conformationUnits">conformationUnits.</param>
        /// <param name="parentId">parentId.</param>
        /// <param name="typeId">typeId.</param>
        /// <param name="modellingRuleId">modellingRuleId.</param>
        /// <param name="designToolOnly">designToolOnly.</param>
        /// <param name="isAbstract">isAbstract.</param>
        /// <param name="children">children.</param>
        public UAVariable(Variant value = default(Variant), string dataType = default(string), int? valueRank = -1, string arrayDimensions = default(string), long? accessLevel = default(long?), decimal? minimumSamplingInterval = default(decimal?), bool? historizing = default(bool?), string nodeId = default(string), NodeClass? nodeClass = Model.NodeClass.UAVariable, string symbolicName = default(string), string browseName = default(string), LocalizedText displayName = default(LocalizedText), LocalizedText description = default(LocalizedText), long? writeMask = default(long?), bool? hasNoPermissions = default(bool?), List<Reference> references = default(List<Reference>), string documentation = default(string), ReleaseStatus? releaseStatus = default(ReleaseStatus?), List<RolePermission> rolePermissions = default(List<RolePermission>), long? accessRestrictions = default(long?), List<string> conformationUnits = default(List<string>), string parentId = default(string), string typeId = default(string), string modellingRuleId = default(string), bool? designToolOnly = default(bool?), bool? isAbstract = default(bool?), ChildList children = default(ChildList)) : base(nodeId, nodeClass, symbolicName, browseName, displayName, description, writeMask, hasNoPermissions, references, documentation, releaseStatus, rolePermissions, accessRestrictions, conformationUnits, parentId, typeId, modellingRuleId, designToolOnly, isAbstract, children)
        {
            this.Value = value;
            this.DataType = dataType;
            // use default value if no "valueRank" provided
            this.ValueRank = valueRank ?? -1;
            this.ArrayDimensions = arrayDimensions;
            this.AccessLevel = accessLevel;
            this.MinimumSamplingInterval = minimumSamplingInterval;
            this.Historizing = historizing;
        }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "Value", EmitDefaultValue = false)]
        public Variant Value { get; set; }

        /// <summary>
        /// Gets or Sets DataType
        /// </summary>
        [DataMember(Name = "DataType", EmitDefaultValue = false)]
        public string DataType { get; set; }

        /// <summary>
        /// Gets or Sets ValueRank
        /// </summary>
        [DataMember(Name = "ValueRank", EmitDefaultValue = true)]
        public int? ValueRank { get; set; }

        /// <summary>
        /// Gets or Sets ArrayDimensions
        /// </summary>
        [DataMember(Name = "ArrayDimensions", EmitDefaultValue = false)]
        public string ArrayDimensions { get; set; }

        /// <summary>
        /// Gets or Sets AccessLevel
        /// </summary>
        [DataMember(Name = "AccessLevel", EmitDefaultValue = true)]
        public long? AccessLevel { get; set; }

        /// <summary>
        /// Gets or Sets MinimumSamplingInterval
        /// </summary>
        [DataMember(Name = "MinimumSamplingInterval", EmitDefaultValue = true)]
        public decimal? MinimumSamplingInterval { get; set; }

        /// <summary>
        /// Gets or Sets Historizing
        /// </summary>
        [DataMember(Name = "Historizing", EmitDefaultValue = true)]
        public bool? Historizing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UAVariable {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  DataType: ").Append(DataType).Append("\n");
            sb.Append("  ValueRank: ").Append(ValueRank).Append("\n");
            sb.Append("  ArrayDimensions: ").Append(ArrayDimensions).Append("\n");
            sb.Append("  AccessLevel: ").Append(AccessLevel).Append("\n");
            sb.Append("  MinimumSamplingInterval: ").Append(MinimumSamplingInterval).Append("\n");
            sb.Append("  Historizing: ").Append(Historizing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected override IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            // AccessLevel (long?) maximum
            if (this.AccessLevel > (long?)4294967296)
            {
                yield return new ValidationResult("Invalid value for AccessLevel, must be a value less than or equal to 4294967296.", new [] { "AccessLevel" });
            }

            // AccessLevel (long?) minimum
            if (this.AccessLevel < (long?)0)
            {
                yield return new ValidationResult("Invalid value for AccessLevel, must be a value greater than or equal to 0.", new [] { "AccessLevel" });
            }

            yield break;
        }
    }

}
